/*
 * Calculator Service
 * Create calculator to calculate numbers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: example@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thoughtworks.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InputRequest
 */
public class InputRequestTest {
    private final InputRequest model = new InputRequest();

    /**
     * Model tests for InputRequest
     */
    @Test
    public void testInputRequest() {
        // TODO: test InputRequest
    }

    /**
     * Test the property 'calcType'
     */
    @Test
    public void calcTypeTest() {
        // TODO: test calcType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'number1'
     */
    @Test
    public void number1Test() {
        // TODO: test number1
    }

    /**
     * Test the property 'number2'
     */
    @Test
    public void number2Test() {
        // TODO: test number2
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
