/*
 * Calculator Service
 * Create calculator to calculate numbers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: example@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thoughtworks.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * InputRequest
 */
@JsonPropertyOrder({
  InputRequest.JSON_PROPERTY_CALC_TYPE,
  InputRequest.JSON_PROPERTY_ID,
  InputRequest.JSON_PROPERTY_NUMBER1,
  InputRequest.JSON_PROPERTY_NUMBER2,
  InputRequest.JSON_PROPERTY_RESULT
})

public class InputRequest {
  public static final String JSON_PROPERTY_CALC_TYPE = "calcType";
  private String calcType;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NUMBER1 = "number1";
  private Integer number1;

  public static final String JSON_PROPERTY_NUMBER2 = "number2";
  private Integer number2;

  public static final String JSON_PROPERTY_RESULT = "result";
  private Integer result;


  public InputRequest calcType(String calcType) {
    
    this.calcType = calcType;
    return this;
  }

   /**
   * Get calcType
   * @return calcType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALC_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCalcType() {
    return calcType;
  }


  public void setCalcType(String calcType) {
    this.calcType = calcType;
  }


  public InputRequest id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public InputRequest number1(Integer number1) {
    
    this.number1 = number1;
    return this;
  }

   /**
   * Get number1
   * @return number1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumber1() {
    return number1;
  }


  public void setNumber1(Integer number1) {
    this.number1 = number1;
  }


  public InputRequest number2(Integer number2) {
    
    this.number2 = number2;
    return this;
  }

   /**
   * Get number2
   * @return number2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumber2() {
    return number2;
  }


  public void setNumber2(Integer number2) {
    this.number2 = number2;
  }


  public InputRequest result(Integer result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResult() {
    return result;
  }


  public void setResult(Integer result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputRequest inputRequest = (InputRequest) o;
    return Objects.equals(this.calcType, inputRequest.calcType) &&
        Objects.equals(this.id, inputRequest.id) &&
        Objects.equals(this.number1, inputRequest.number1) &&
        Objects.equals(this.number2, inputRequest.number2) &&
        Objects.equals(this.result, inputRequest.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calcType, id, number1, number2, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputRequest {\n");
    sb.append("    calcType: ").append(toIndentedString(calcType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number1: ").append(toIndentedString(number1)).append("\n");
    sb.append("    number2: ").append(toIndentedString(number2)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

